import fs from 'fs';
let p = fs.readFileSync('src/components/Progress.tsx', 'utf-8');

p = p.replace(
  '{weaknesses.length > 0 ? weaknesses.map(t => (\\n                 <div key={t.id} className="bg-surface-alt p-5 rounded-2xl border border-border flex items-center justify-between shadow-sm">\\n                    <span className="font-semibold text-ink line-clamp-1 flex-1 mr-4">{t.title}</span>\\n                    {t.attempted ? (\\n                        <span className="font-bold font-mono text-accent-warm bg-accent-warm/10 px-3 py-1 rounded-full text-sm">{t.percent}%</span>\\n                    ) : (\\n                        <span className="text-xs font-bold text-slate-500 uppercase flex items-center gap-1 bg-slate-100 px-3 py-1 rounded-full"><AlertCircle className="w-3 h-3"/> Not yet tested</span>\\n                    )}\\n                 </div>\\n             )) : (\\n                 <div className="p-6 bg-surface border border-border rounded-2xl text-center text-sm text-slate-500">\\n                    Start learning to see your focus areas.\\n                 </div>\\n             )}',
  '{weaknesses.length > 0 ? weaknesses.map(t => (\\n                 <div key={t.id} className="bg-surface-alt p-5 rounded-2xl border border-border flex items-center justify-between shadow-sm">\\n                    <span className="font-semibold text-ink line-clamp-1 flex-1 mr-4">{t.title}</span>\\n                    {t.attempted ? (\\n                        <span className="font-bold font-mono text-accent-warm bg-accent-warm/10 px-3 py-1 rounded-full text-sm">{t.percent}%</span>\\n                    ) : (\\n                        <span className="text-xs font-bold text-slate-500 uppercase flex items-center gap-1 bg-slate-100 px-3 py-1 rounded-full"><AlertCircle className="w-3 h-3"/> Not yet tested</span>\\n                    )}\\n                 </div>\\n             )) : (\\n                 <div className="p-6 bg-surface border border-border rounded-2xl text-center text-sm text-slate-500">\\n                    Take more quizzes to identify your focus areas.\\n                 </div>\\n             )}'
);

fs.writeFileSync('src/components/Progress.tsx', p);
